spring:
  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
