spring:
  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
